2019/02/15 22:38:44 [error] 5127#5127: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 22:39:34 [error] 5127#5127: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 22:39:35 [error] 5127#5127: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 22:39:37 [error] 5127#5127: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 22:40:01 [error] 5186#5186: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 22:42:39 [error] 5186#5186: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 22:50:15 [error] 5462#5462: *47 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 23:23:46 [error] 2077#2077: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 23:23:49 [error] 2077#2077: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 23:26:00 [error] 3160#3160: *39 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 23:27:16 [error] 3419#3419: *41 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 23:28:29 [error] 3419#3419: *59 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 23:29:21 [error] 3419#3419: *59 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 23:29:39 [error] 3419#3419: *59 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 08:33:29 [error] 904#904: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 08:33:31 [error] 904#904: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 08:33:32 [error] 904#904: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 08:33:33 [error] 904#904: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 08:52:24 [error] 10405#10405: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 08:52:26 [error] 10405#10405: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 09:05:20 [error] 10754#10754: *59 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 09:07:45 [error] 10834#10834: *67 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 09:14:48 [error] 11019#11019: *86 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 09:14:50 [error] 11019#11019: *86 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 09:26:51 [error] 11276#11276: *109 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/28 12:59:17 [error] 876#876: *62 FastCGI sent in stderr: "PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2-debug/src/LogTarget.php on line 85" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /users HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test"
2019/02/28 12:59:23 [error] 876#876: *65 FastCGI sent in stderr: "PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2-debug/src/LogTarget.php on line 85" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /user HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test"
2019/03/03 21:28:43 [error] 898#898: *388 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to get property 'username' of non-object in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php on line 112
PHP message: PHP Notice:  Trying to get property 'username' of non-object in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php on line 121
PHP message: PHP Notice:  Trying to get property 'email' of non-object in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php on line 122" while reading response header from upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/03 22:42:54 [error] 898#898: *672 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function getThumbUploadUrl() on null in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php:111
Stack trace:
#0 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#2 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/pavel/Gee...', Array," while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/03 22:42:54 [error] 898#898: *672 FastCGI sent in stderr: " NULL)
#3 /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/main.php(39): yii\base\View->render('header.php', Array)
#4 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require('/home/pavel/Gee...')
#5 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#6 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/home/pavel/Gee...'" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/05 22:28:01 [error] 940#940: *172 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function getThumbUploadUrl() on null in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php:111
Stack trace:
#0 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#2 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/pavel/Gee...', Array," while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/05 22:28:01 [error] 940#940: *172 FastCGI sent in stderr: " NULL)
#3 /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/main.php(39): yii\base\View->render('header.php', Array)
#4 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require('/home/pavel/Gee...')
#5 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#6 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/home/pavel/Gee...'" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/05 22:28:01 [error] 940#940: *172 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function getThumbUploadUrl() on null in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php:111
Stack trace:
#0 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#2 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/pavel/Gee...', Array," while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/05 22:28:01 [error] 940#940: *172 FastCGI sent in stderr: " NULL)
#3 /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/main.php(39): yii\base\View->render('header.php', Array)
#4 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require('/home/pavel/Gee...')
#5 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#6 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/home/pavel/Gee...'" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/06 20:48:24 [error] 940#940: *243 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function getThumbUploadUrl() on null in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php:111
Stack trace:
#0 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#2 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/pavel/Gee...', Array," while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/06 20:48:24 [error] 940#940: *243 FastCGI sent in stderr: " NULL)
#3 /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/main.php(39): yii\base\View->render('header.php', Array)
#4 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require('/home/pavel/Gee...')
#5 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#6 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/home/pavel/Gee...'" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/06 20:48:24 [error] 940#940: *243 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function getThumbUploadUrl() on null in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php:111
Stack trace:
#0 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#2 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/pavel/Gee...', Array," while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/06 20:48:24 [error] 940#940: *243 FastCGI sent in stderr: " NULL)
#3 /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/main.php(39): yii\base\View->render('header.php', Array)
#4 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require('/home/pavel/Gee...')
#5 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#6 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/home/pavel/Gee...'" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/09 12:58:35 [error] 925#925: *841 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ',' in /home/pavel/Geekbrains/adv/common/services/ProjectService.php on line 30" while reading response header from upstream, client: 127.0.0.1, server: backend.test, request: "POST /project/update?id=1 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/project/update?id=1"
2019/03/09 12:58:47 [error] 925#925: *841 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ',' in /home/pavel/Geekbrains/adv/common/services/ProjectService.php on line 30" while reading response header from upstream, client: 127.0.0.1, server: backend.test, request: "GET /project/update?id=1 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/project/view?id=1"
2019/03/09 12:58:48 [error] 925#925: *841 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ',' in /home/pavel/Geekbrains/adv/common/services/ProjectService.php on line 30" while reading response header from upstream, client: 127.0.0.1, server: backend.test, request: "GET /project/view?id=1 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/project/"
2019/03/09 12:58:49 [error] 925#925: *841 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ',' in /home/pavel/Geekbrains/adv/common/services/ProjectService.php on line 30" while reading response header from upstream, client: 127.0.0.1, server: backend.test, request: "GET /project/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test"
2019/03/09 18:02:31 [error] 925#925: *1054 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /home/pavel/Geekbrains/adv/backend/controllers/UserController.php on line 136. in /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /home/pavel/Geekbrains/adv/backend/controllers/UserController.php on line 136. in /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /h" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /user/profile HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test"
2019/03/09 19:21:12 [error] 925#925: *1430 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function getThumbUploadUrl() on null in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php:111
Stack trace:
#0 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#2 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/pavel/Gee...', Array," while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/09 19:21:12 [error] 925#925: *1430 FastCGI sent in stderr: " NULL)
#3 /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/main.php(39): yii\base\View->render('header.php', Array)
#4 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require('/home/pavel/Gee...')
#5 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#6 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/home/pavel/Gee...'" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/09 19:21:12 [error] 925#925: *1430 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function getThumbUploadUrl() on null in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php:111
Stack trace:
#0 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#2 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/pavel/Gee...', Array," while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/09 19:21:12 [error] 925#925: *1430 FastCGI sent in stderr: " NULL)
#3 /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/main.php(39): yii\base\View->render('header.php', Array)
#4 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require('/home/pavel/Gee...')
#5 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#6 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/home/pavel/Gee...'" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/09 19:46:47 [error] 926#926: *1643 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function getThumbUploadUrl() on null in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php:111
Stack trace:
#0 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#2 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/pavel/Gee...', Array, NULL)
#3 /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/main.php(39): yii\base\View->render('header" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/09 19:46:47 [error] 926#926: *1643 FastCGI sent in stderr: ".php', Array)
#4 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require('/home/pavel/Gee...')
#5 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#6 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/home/pavel/Gee...'" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/09 19:46:47 [error] 927#927: *1644 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function getThumbUploadUrl() on null in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php:111
Stack trace:
#0 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#2 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/pavel/Gee...', Array, NULL)
#3 /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/main.php(39): yii\base\View->render('header" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/09 19:46:47 [error] 927#927: *1644 FastCGI sent in stderr: ".php', Array)
#4 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require('/home/pavel/Gee...')
#5 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#6 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/home/pavel/Gee...'" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/10 21:46:31 [error] 925#925: *1772 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function getThumbUploadUrl() on null in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php:111
Stack trace:
#0 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#2 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/pavel/Gee...', Array," while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/10 21:46:31 [error] 925#925: *1772 FastCGI sent in stderr: " NULL)
#3 /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/main.php(39): yii\base\View->render('header.php', Array)
#4 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require('/home/pavel/Gee...')
#5 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#6 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/home/pavel/Gee...'" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/10 21:46:32 [error] 927#927: *1777 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function getThumbUploadUrl() on null in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php:111
Stack trace:
#0 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#2 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/pavel/Gee...', Array," while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/10 21:46:32 [error] 927#927: *1777 FastCGI sent in stderr: " NULL)
#3 /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/main.php(39): yii\base\View->render('header.php', Array)
#4 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require('/home/pavel/Gee...')
#5 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#6 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/home/pavel/Gee...'" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/15 21:00:13 [error] 1143#1143: *174 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function getThumbUploadUrl() on null in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php:111
Stack trace:
#0 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#2 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/pavel/Gee...', Array," while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/15 21:00:13 [error] 1143#1143: *174 FastCGI sent in stderr: " NULL)
#3 /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/main.php(39): yii\base\View->render('header.php', Array)
#4 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require('/home/pavel/Gee...')
#5 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#6 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/home/pavel/Gee...'" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/15 21:00:13 [error] 1142#1142: *179 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function getThumbUploadUrl() on null in /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/header.php:111
Stack trace:
#0 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#2 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/pavel/Gee...', Array," while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
2019/03/15 21:00:13 [error] 1142#1142: *179 FastCGI sent in stderr: " NULL)
#3 /home/pavel/Geekbrains/adv/backend/views/layouts/admin-lte/main.php(39): yii\base\View->render('header.php', Array)
#4 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(348): require('/home/pavel/Gee...')
#5 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/home/pavel/Gee...', Array)
#6 /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/home/pavel/Gee...'" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /assets/2af6ed3b/js/app.min.js HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test", referrer: "http://backend.test/site/login"
